// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCHIE4gAPi9xmcX_RxsTPEl-4INAK-XPIM',
    appId: '1:545630676535:web:d307c459fb7242cf6501b2',
    messagingSenderId: '545630676535',
    projectId: 'labtest-alya',
    authDomain: 'labtest-alya.firebaseapp.com',
    storageBucket: 'labtest-alya.firebasestorage.app',
    measurementId: 'G-WEJ3MC0M68',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCBKHMMLRvUyGSRnOWDD-fcHNWcZXIYnsc',
    appId: '1:545630676535:android:5ea06828d270f2706501b2',
    messagingSenderId: '545630676535',
    projectId: 'labtest-alya',
    storageBucket: 'labtest-alya.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBlSIKclzlwDnnWCQW2g4S4UrFPynCOiR4',
    appId: '1:545630676535:ios:42aaa2ba69267f206501b2',
    messagingSenderId: '545630676535',
    projectId: 'labtest-alya',
    storageBucket: 'labtest-alya.firebasestorage.app',
    iosBundleId: 'com.example.labTest',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBlSIKclzlwDnnWCQW2g4S4UrFPynCOiR4',
    appId: '1:545630676535:ios:42aaa2ba69267f206501b2',
    messagingSenderId: '545630676535',
    projectId: 'labtest-alya',
    storageBucket: 'labtest-alya.firebasestorage.app',
    iosBundleId: 'com.example.labTest',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCHIE4gAPi9xmcX_RxsTPEl-4INAK-XPIM',
    appId: '1:545630676535:web:4ed250ccc3fdff2f6501b2',
    messagingSenderId: '545630676535',
    projectId: 'labtest-alya',
    authDomain: 'labtest-alya.firebaseapp.com',
    storageBucket: 'labtest-alya.firebasestorage.app',
    measurementId: 'G-4NN70L1M26',
  );
}
